export default {
  PRODUCT: {
    GET: 'PRODUCT_GET',
    GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
    GET_ERROR: 'PRODUCT_GET_ERROR',
  },
  USER: {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
  },
  CHECKOUT: {
    ADD_PRODUCT: 'CHECKOUT_ADD_PRODUCT',
    REMOVE_PRODUCT: 'CHECKOUT_REMOVE_PRODUCT',
  },
};
